version: '3.3'

services:
  wordpress_db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    volumes:
       - ./data:/var/lib/mysql
       - ./mysql-conf/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASS}
      TZ: 'Asia/Tokyo'
    networks: 
      app_net: 
        ipv4_address: '172.18.0.2'

  wordpress_php:
    image: wordpress:5-fpm
    container_name: wordpress_php
    depends_on:
       - wordpress_db
    restart: always
    volumes:
       - ./wordpress:/var/www/html
       - ./php-conf/php.ini:/usr/local/etc/php/php.ini
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PASS}
      TZ: 'Asia/Tokyo'
    networks: 
      app_net: 
        ipv4_address: '172.18.0.3'

  wordpress_web:
    image: nginx
    container_name: wordpress_web
    depends_on:
       - wordpress_php
    restart: always
    volumes:
       - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
       - ./wordpress:/var/www/html
       - ./web-logs:/var/log/nginx
    environment:
      TZ: 'Asia/Tokyo'
    networks: 
      app_net: 
        ipv4_address: '172.18.0.4'

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    depends_on:
       - wordpress_web
    ports:
       - '80:80'
       - '443:443'
    restart: always
    volumes:
       - ./ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: '${HOST_DOMAIN} -> http://wordpress_web:80/'
      STAGE: '${PRODUCTION_STAGE}'
      CLIENT_MAX_BODY_SIZE: 64M
      TZ: 'Asia/Tokyo'
    networks: 
      app_net: 
        ipv4_address: '172.18.0.5'

networks:
  app_net: 
    driver: bridge
    ipam: 
      driver: default
      config:
       - subnet: '172.18.0.0/16'
